// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Configuration struct {
	ID                    int64
	ConfigName            string
	ConfigType            string
	RxName                sql.NullString
	TxName                sql.NullString
	TpName                sql.NullString
	PayloadName           sql.NullString
	TSMConfigurationName  string
	CortexIFM             sql.NullInt64
	IntermediateFrequency sql.NullInt64
	ProgrammableAttnUsed  sql.NullString
	DeviceProfileName     string
}

type Device struct {
	ID                   int64
	DeviceName           string
	DeviceMake           string
	DeviceType           string
	IPAddress            string
	ControlPort          int64
	AlternateControlPort sql.NullInt64
	ReadPort             sql.NullInt64
	DopplerPort          sql.NullInt64
	TimeoutInMillisecs   int64
}

type DeviceProfile struct {
	ID                int64
	DeviceProfileName string
	SAName            sql.NullString
	VSAName           sql.NullString
	PMName            sql.NullString
	PPMName           sql.NullString
	TSMName           sql.NullString
	GTxName           sql.NullString
	SGName            sql.NullString
	VSGName           sql.NullString
}

type DownlinkLoss struct {
	ID            int64
	ConfigName    string
	TestPhaseName string
	Profile       string
}

type DownlinkPowerProfile struct {
	ID         int64
	Name       sql.NullString
	PMChannel  string
	OccupiedBW int64
}

type FrequencyProfile struct {
	ID                 int64
	Name               string
	MaxFrequency       sql.NullFloat64
	StepSize           sql.NullFloat64
	CommandingRequired string
	DopplerFile        sql.NullString
}

type LossMeasurementFrequency struct {
	ID          int64
	Description string
	Frequency   float64
}

type PowerProfile struct {
	ID                        int64
	Name                      string
	PowerLevels               string
	NoOfCommandsAtThreshold   int64
	NoOfCommandsAtOtherLevels int64
}

type PulseProfile struct {
	ID                int64
	Name              string
	TransientON       float64
	IQOn              int64
	AcquisitionTime   int64
	SweepTime         float64
	SweepCount        int64
	FilterType        string
	FilterBandwidth   float64
	YTop              float64
	ThresholdLevel    float64
	Hysterisis        float64
	PPMTriggerLevel   float64
	PPMReferenceLevel float64
	PPMYDivision      float64
	PPMChannel        string
}

type SpecPL struct {
	SpecID                      int64
	ConfigName                  string
	ResolutionMode              sql.NullString
	OnTime                      float64
	CenterFrequency             float64
	UplinkPower                 float64
	PeakPower                   sql.NullFloat64
	PeakPowerTolerance          sql.NullFloat64
	AveragePower                sql.NullFloat64
	AveragePowerTolerance       sql.NullFloat64
	DutyCycle                   sql.NullFloat64
	DutyCycleTolerance          sql.NullFloat64
	PulsePeriod                 float64
	PulsePeriodTolerance        sql.NullFloat64
	ReplicaPeriod               sql.NullFloat64
	ReplicaPeriodTolerance      sql.NullFloat64
	PulseWidth                  float64
	PulseWidthTolerance         sql.NullFloat64
	PulseSeperation             sql.NullFloat64
	PulseSeperationTolerance    sql.NullFloat64
	RiseTime                    sql.NullFloat64
	RiseTimeTolerance           sql.NullFloat64
	FallTime                    sql.NullFloat64
	FallTimeTolerance           sql.NullFloat64
	AverageTxPower              sql.NullFloat64
	AverageTxPowerTolerance     sql.NullFloat64
	ChirpBandwidth              sql.NullFloat64
	ChirpBandwidthTolerance     sql.NullFloat64
	RepetitionRate              sql.NullFloat64
	RepetitionRateTolerance     sql.NullFloat64
	ReplicaRate                 sql.NullFloat64
	ReplicaRateTolerance        sql.NullFloat64
	FrequencyShift              sql.NullFloat64
	FrequencyShiftTolerance     sql.NullFloat64
	Droop                       sql.NullFloat64
	DroopTolerance              sql.NullFloat64
	Phase                       sql.NullFloat64
	PhaseTolerance              sql.NullFloat64
	Overshoot                   sql.NullFloat64
	OvershootTolerance          sql.NullFloat64
	ChirpRate                   sql.NullFloat64
	ChirpRateTolerance          sql.NullFloat64
	ChirpRateDeviation          sql.NullFloat64
	ChirpRateDeviationTolerance sql.NullFloat64
	Ripple                      sql.NullFloat64
	RippleTolerance             sql.NullFloat64
}

type SpecRx struct {
	ID                    int64
	RxName                string
	Frequency             int64
	MaxPower              float64
	TCSubCarrierFrequency float64
	ModulationScheme      string
	AcquisitionOffset     sql.NullFloat64
	SweepRange            sql.NullFloat64
	SweepRate             sql.NullFloat64
	TCModIndex            sql.NullFloat64
	FrequencyDeviationFM  sql.NullFloat64
	CodeRateInMcps        sql.NullFloat64
}

type SpecRxTMTC struct {
	RxName                 string
	LockStatusMnemonic     sql.NullString
	LockStatusValue        sql.NullString
	BSLockStatusMnemonic   string
	BSLockStatusValue      string
	AGCMnemonic            string
	LoopStressMnemonic     sql.NullString
	CommandCounterMnemonic string
	TestCommandSet         string
	TestCommandReset       string
}

type SpecTp struct {
	TpID   int64
	TpName sql.NullString
	RxName string
	TxName string
}

type SpecTpRanging struct {
	TpName                                string
	RangingID                             int64
	RangingName                           string
	ToneFrequency                         float64
	UplinkToneMIOnlyRanging               float64
	UplinkToneMISimultaneousCmdAndRanging sql.NullFloat64
	TCMISimultaneousCmdAndRanging         float64
	DownlinkMI                            float64
	AllowedDownlinkMIDeviation            float64
	AvailableForCommanding                string
}

type SpecTx struct {
	TxID                      int64
	TxName                    string
	Frequency                 int64
	Power                     float64
	Spurious                  float64
	Harmonics                 float64
	AllowedFrequencyDeviation float64
	AllowedPowerDevaition     float64
	ModulationScheme          string
	IsBurst                   string
	BurstTime                 sql.NullFloat64
}

type SpecTxHarmonic struct {
	TxName              string
	HarmonicsID         int64
	HarmonicType        string
	HarmonicsName       string
	Frequency           float64
	TotalLossFromTxToSA float64
}

type SpecTxSubCarrier struct {
	TxName                   string
	SubCarrierID             int64
	SubCarrierName           string
	Frequency                float64
	ModIndex                 sql.NullFloat64
	AllowedModIndexDeviation sql.NullFloat64
	PeakFrequencyDeviation   sql.NullFloat64
	AlwaysPresent            string
}

type SpectrumProfile struct {
	ID              int64
	Name            string
	CenterFrequency float64
	Span            float64
	RBW             int64
	VBW             int64
}

type TMProfile struct {
	ID             int64
	Name           string
	PreRequisiteTM sql.NullString
	LogTM          sql.NullString
}

type TRMProfile struct {
	ID                         int64
	Name                       sql.NullString
	NoOfTRMs                   int64
	TimePerTRMInSecs           float64
	DelayBeforeFirstReadInSecs float64
}

type TSMConfiguration struct {
	ID              int64
	Name            string
	UplinkToSC      sql.NullString
	IncludePad      sql.NullString
	ExcludePad      sql.NullString
	UplinkToSA      sql.NullString
	UplinkToPM      sql.NullString
	TerminateUplink sql.NullString
	DownlinkToSA    sql.NullString
	DownlinkToPM    sql.NullString
	AttnNumber      sql.NullInt64
	DownlinkToDC    sql.NullString
	InputPortName   sql.NullString
	SAPortName      sql.NullString
	PMPortName      sql.NullString
	OutputPortName  sql.NullString
}

type Test struct {
	ID                       int64
	ConfigName               string
	TestType                 string
	TestCategory             string
	ULProfileName            sql.NullString
	DLProfileName            sql.NullString
	PowerProfileName         sql.NullString
	FrequencyProfileName     sql.NullString
	DownlinkPowerProfileName sql.NullString
	PulseProfileName         sql.NullString
	TRMProfileName           sql.NullString
	TMProfileName            sql.NullString
}

type TestPhase struct {
	ID           int64
	Name         string
	CreationDate sql.NullString
	CreationTime sql.NullString
	Selected     int64
}

type UpDownConverter struct {
	ID               int64
	Name             string
	InputFrequency   float64
	OutputFrequency  float64
	MaxPowerCable    float64
	MinPowerCable    float64
	MaxPowerRadiated sql.NullFloat64
	MinPowerRadiated sql.NullFloat64
}

type UplinkLoss struct {
	ID            int64
	ConfigName    string
	TestPhaseName string
	Profile       string
}
